config/routes.rb
Rails.application.routes.draw do
  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations'}
  resources :links do
    member do
      put "like", to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
  end

  get "/latest", to: "links#latest"

  get "/popular", to: "links#index"

  root to: "links#index"

end

app/models/link.rb
class Link < ActiveRecord::Base
  acts_as_votable
	belongs_to :user
	before_save :update_score

  def score
    ::Score.new(get_likes.count, get_dislikes.count, self.created_at || Time.now).value
  end

  def is_owner?(user)
    self.user_id == user_id
  end

  private

  def update_score
  	if cached_votes_total_changed?
  		self.score = score
  	end
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  rescue_from Pundit::NotAuthorizedError, :with => :record_not_found

  # GET /links
  # GET /links.json
  def index
    @links = Link.all.order(:score)
  end

  def latest
    @links = Link.all.order(created_at: :desc)
    render :index
  end

  # GET /links/1
  # GET /links/1.json
  def show
    authorize @link
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
    authorize @link
  end

  # POST /links
  # POST /links.json
  def create

    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    authorize @link
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    authorize @link
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user

    if request.xhr?
      render json: { count: @link.get_upvotes.size, id: params[:id] }
    else
      redirect_to @link
    end
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_from current_user
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    def record_not_found
      redirect_to links_url, :alert => "Couldn't find post"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url, :image, :description, :provider_name, :provider_url)
    end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= bootstrap_form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="submit-web">
    <input class="submit-web-input" type="url" name="link[image]" id="link_image" placeholder="http://">
    <img id="submit-web-image" src=""/>
  </div>

  <div class="submit-web-actions">
    <div class="field">
      <input class="form-control" type="text" name="link[title]" id="link_title" placeholder="Enter Title">
    </div>

    <div class="field">
      <input class="form-control" type="text" name="link[url]" id="link_url" placeholder="Purchase URL">
    </div>

    <div class="field">
      <input class="form-control" type="text" name="link[tags]" id="link_tags" placeholder="#addsometags">
    </div>



    <div class="actions">
      <input type="submit" name="commit" value="Create Link" class="btn btn-default success">
    </div>

  </div>



  <script>
    $('#link_image').on('paste', function () {
      var element = this;
      setTimeout(function () {
        var text = $(element).val();
        var image = $('#submit-web-image')
        $( image ).attr( "src", text );
        $( image ).css( "opacity", "1" );
        $( element ).css( "display", "none" );
        $('.submit-web-actions' ).css( "display", "block" ); 
      }, 100);
    });
  </script>

<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>
<% else %>
  <div class="container header">
    <div class="row">
      <div class="col-md-9 text-left">
        <h1>Over <%= @links.count %> products picked by us - for everyone.</br>Our community is certainly a fashionable bunch.</h1>
        <p>Request an invite for free and join our great community.</p>
      </div>
      <div class="col-md-3">
        <a class="btn btn-request-invite">Request Invite →</a>
      </div>
    </div>
  </div>
<% end %>

<div class="container-fluid main-content">



  <div class="grid">
  <% @links.each do |link| %>

      <div class="item">


          <div class="hover-info">

        <% if current_user.liked? link %>

          <%= link_to like_link_path(link), class: "vote", method: :put, remote: true do %>
            <div class="hover-score-liked">

              <p class="hover-actual-score" data-id="<%= link[:id] %>">
                <%= link.get_upvotes.size %>
              </p>

              <p class="hover-plus-score"><i class="fa fa-heart fa-lg"></i></p>
            </div>
          <% end %>

        <% else %>

          <%= link_to like_link_path(link), class: "vote", method: :put, remote: true do %>
            <div class="hover-score">

              <p class="hover-actual-score" data-id="<%= link[:id] %>">
                <%= link.get_upvotes.size %>
              </p>

              <p class="hover-plus-score"><i class="fa fa-heart fa-lg"></i></p>
            </div>
          <% end %>
          
        <% end %>

          <a target='_blank' href="<%= link.url %>">
            <div class="hover-basket">
              <p class="hover-cart"><i class="fa fa-shopping-cart fa-lg"></i></p>
            </div>

            <div class="hover-avatar">
              <img class="img-responsive" src="<%= link.user.avatar %>"/>
            </div>
          </a>

          </div>
          <%= link_to link_path(link) do %>
            <img class="link-image" src="<%= link.image %>"/>
          <% end %>

      
  <% end %>

  </div>
</div>
<br>


<script>
    $('.grid').gridalicious({
      width: 240,
      animate: true,
      gutter: 20
    });

</script>

app/views/links/new.html.erb
<div class="container new-product">
			<div class="row">

				<div class="col-md-4 col-md-offset-1">
					<div class="col-md-12 white-background">
						<div class="wrapper">
							<h1>Submit Product</h1>
							<p>Submit a product below and it will be sent to Pinatta to be viewed & admired by thousands, please try and post as much information as possible.</p>
						</div>
					</div>
				</div>

				<div class="col-md-6">
					<div class="col-md-12 white-background">
						<div class="wrapper">
							<%= render 'form' %>
						</div>
					</div>
				</div>

			</div>

</div>