config/routes.rb
Rails.application.routes.draw do
  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations'}
  resources :links do
    member do
      put "like", to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
  end

  get "/latest", to: "links#latest"

  get "/popular", to: "links#index"

  root to: "links#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinatta - Find Smashing Products.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <script src="http://cdn.embed.ly/jquery.embedly-3.0.5.min.js" type="text/javascript"></script>
  <script src="http://cdn.embed.ly/jquery.preview-0.3.2.min.js" type="text/javascript"></script>

  <script src="//cdn.jsdelivr.net/headroomjs/0.7.0/headroom.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/headroom/0.7.0/jQuery.headroom.min.js"></script>

  <script data-cfasync="false" type="text/javascript" src="//filamentapp.s3.amazonaws.com/48e28495c5cb10e99a3a77be965046de.js" async="async"></script>

</head>
<body>


<nav class="navbar navbar-default navbar-fixed-top">

  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

      <div class="navbar-brand">
        <a class="brand-container" href="/">
        </a>
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/latest">Latest</span></a></li>
        <li><a href="/popular">Popular</a></li>
        <li><a href="#">Tags</a></li>
        <li><a href="#">Search</a></li>
      </ul>

      <% if user_signed_in? %>

      <ul class="nav navbar-nav navbar-right">

        <li class="submit-special">
          <%= link_to new_link_path do %>
            <button type="button" class="btn btn-primary">+</button>
          <% end %>
        </li>

        <li class="user-score">
          <a class="btn btn-primary user-score-button"><%= current_user.points %></a>
        </li>

       <li class="dropdown">
          <a class="nav-avatar-custom dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false">
            <div class="avatar">
              <img class="img-responsive" src="<%= current_user.avatar %>"/>
            </div>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Account', edit_user_registration_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      </ul>

      <% else %>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to new_link_path, "data-toggle" => "modal", 'data-target' => '#sign-up-modal' do %>
            Submit
          <% end %>
        </li>
        <li>
          <a class="login-menubar" data-toggle="modal" data-target=".login">Login</a>
        </li>
      </ul>

      <div class="modal fade bs-example-modal-sm" id="sign-up-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">

              <div class="row">
                <div class="col-md-12 text-center">
                  <h1>Hey, Please sign in below to submit!</h1>
                  <p>To keep the community in top-notch shape we require people to use their social profiles - We promise not to post anything without your consent. </p>
                </div>
              </div>

              <div class="row">
                <div class="col-md-12 text-center">
                  <%= link_to user_omniauth_authorize_path(:twitter) do %>
                    <button type="button" class="btn btn-default sign-in-button sign-in-with-twitter"><i class="fa fa-twitter fa-2x"></i> Sign in with Twitter</button>
                  <% end %>
                  <%= link_to user_omniauth_authorize_path(:facebook) do %>
                    <button type="button" class="btn btn-default sign-in-button sign-in-with-facebook"><i class="fa fa-facebook fa-2x"></i> Sign in with Facebook</button>
                  <% end %>
                </div>
              </div>

          </div>
        </div>
      </div>

      <div class="modal fade login" tabindex="-1" role="dialog" aria-labelledby="login" aria-hidden="true">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">

              <div class="row">
                <div class="col-md-12 text-center">
                  <h1>Welcome back to Bundel</h1>
                  <p>To keep the community in top-notch shape we require people to use their social profiles - We promise not to post anything without your consent. </p>
                </div>
              </div>

              <div class="row">
                <div class="col-md-12 text-center">
                  <%= link_to user_omniauth_authorize_path(:twitter) do %>
                    <button type="button" class="btn btn-default sign-in-button sign-in-with-twitter"><i class="fa fa-twitter fa-2x"></i> Sign in with Twitter</button>
                  <% end %>
                  <%= link_to user_omniauth_authorize_path(:facebook) do %>
                    <button type="button" class="btn btn-default sign-in-button sign-in-with-facebook"><i class="fa fa-facebook fa-2x"></i> Sign in with Facebook</button>
                  <% end %>
                </div>
              </div>

          </div>
        </div>
      </div>

      <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

<script>
  $(".navbar").headroom({
    "offset": 100
  });
</script>

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-54ea069211fb693b" async="async"></script>


</body>
</html>